version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: eventmanagementsystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zxc993
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Хранение данных PostgreSQL

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eventmanagementsystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: zxc993
    depends_on:
      - postgres

volumes:
  postgres-data:
