spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/eventmanagementsystem
        username: postgres
        password: zxc993
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            format_sql: true
        properties:
            hibernate:
                format_sql: true
